# -*- coding: utf-8 -*-
"""DAA PROJECT[SL].ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1MOhTkSHLWQmCv8A9UcvCRGsEFMx9R9d0
"""

import streamlit as st
import pandas as pd
import matplotlib.pyplot as plt

# ---------- Title and Description ----------
st.title("🚚 Fractional Knapsack – Cargo Loading App")
st.write("""
This app demonstrates the **Fractional Knapsack (Greedy Algorithm)**
to optimize cargo loading for maximum profit.
""")

# ---------- Step 1: Upload or Load Dataset ----------
uploaded_file = st.file_uploader("📂 Upload CSV file", type=["csv"])

if uploaded_file is not None:
    df = pd.read_csv(uploaded_file)
else:
    st.info("Using default dataset: `knapsack_5_items_new.csv`")
    df = pd.read_csv("knapsack_5_items_new.csv")

# ---------- Step 2: Select Row ----------
row_index = st.number_input(
    "Select a row index to test (0 - {})".format(len(df)-1),
    min_value=0,
    max_value=len(df)-1,
    value=0
)
row = df.iloc[int(row_index)]
capacity = row["Capacity"]

cargo_names = ["Rice", "Wheat", "Oil", "Sugar", "Flour"]

# Convert weights & profits
items = []
for i, name in enumerate(cargo_names, start=1):
    items.append({
        "Item": name,
        "Weight": row[f"W{i}"],
        "Profit": row[f"P{i}"]
    })

data = pd.DataFrame(items)
data["Ratio"] = data["Profit"] / data["Weight"]

# ---------- Step 3: Fractional Knapsack ----------
def fractional_knapsack(capacity, items):
    items = items.sort_values(by="Ratio", ascending=False)
    total_profit = 0.0
    load_plan = []
    for _, row in items.iterrows():
        if capacity == 0:
            break
        if row["Weight"] <= capacity:
            capacity -= row["Weight"]
            total_profit += row["Profit"]
            load_plan.append((row["Item"], row["Weight"], row["Profit"], 1.0))
        else:
            fraction = capacity / row["Weight"]
            total_profit += row["Profit"] * fraction
            load_plan.append((row["Item"], row["Weight"] * fraction, row["Profit"] * fraction, fraction))
            capacity = 0
    return total_profit, load_plan

# ---------- Step 4: Run Algorithm ----------
max_profit, plan = fractional_knapsack(capacity, data)

st.subheader("💰 Maximum Profit (Fractional):")
st.success(f"{max_profit:.2f}")

st.subheader("📦 Load Plan:")
plan_df = pd.DataFrame(plan, columns=["Item", "Weight Taken", "Profit Earned", "Fraction Used"])
st.dataframe(plan_df)

# ---------- Step 5: Visualization ----------
selected_items = [p[0] for p in plan]
selected_weights = [p[1] for p in plan]
skipped_items = list(set(data["Item"]) - set(selected_items))
skipped_weights = [data.loc[data["Item"] == s, "Weight"].values[0] for s in skipped_items]

fig, ax = plt.subplots(figsize=(8,5))
ax.bar(selected_items, selected_weights, color="green", label="Selected Cargo")
ax.bar(skipped_items, skipped_weights, color="red", label="Skipped Cargo")
ax.set_xlabel("Items")
ax.set_ylabel("Weight Loaded (kg)")
ax.set_title("Cargo Selection using Fractional Knapsack")
ax.legend()
st.pyplot(fig)